/**
 * generated by Xtext
 */
package de.htwg.seapal.components.validation;

import de.htwg.seapal.components.validation.AbstractComponentValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ComponentValidator extends AbstractComponentValidator {
}
