/*
 * generated by Xtext
 */
package de.htwg.seapal.components.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ComponentUiModule extends de.htwg.seapal.components.ui.AbstractComponentUiModule {
	public ComponentUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
