/*
 * generated by Xtext
 */
package de.htwg.seapal.components;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ComponentRuntimeModule extends de.htwg.seapal.components.AbstractComponentRuntimeModule {

}
