/*
* generated by Xtext
*/
package de.htwg.seapal.components.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ComponentAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/htwg/seapal/components/parser/antlr/internal/InternalComponent.tokens");
	}
}
