/*
* generated by Xtext
*/
package de.htwg.seapal.components;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ComponentUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.htwg.seapal.components.ui.internal.ComponentActivator.getInstance().getInjector("de.htwg.seapal.components.Component");
	}
	
}
